### ISSUE TITLE
ActionController::ParameterMissing in GamesController#update

### ISSUE THREAD

**Issue by kirbygit** [TheCorrespondingSquares/chess-app#47]
- param is missing or the value is empty:game
- when another user creates a game then another user tried to join the game [error]
<img width="1032" alt="screen shot 2017-06-10 at 9 50 08 am" src="https://user-images.githubusercontent.com/20747057/27004813-1a156ca4-4dc5-11e7-98b9-6308b9f3624e.png">

cc @fistoriza and me

**Comment by jwmunn** [comment]
`join_params` updated to resolve error.
