### ISSUE TITLE
Horse and Bishop are not in the right default position 

### ISSUE THREAD

**Issue by kirbygit** [TheCorrespondingSquares/chess-app#53]
Wrong Position of Horse and Bishop
<img width="672" alt="screen shot 2017-06-14 at 10 46 30 pm" src="https://user-images.githubusercontent.com/20747057/27167016-58686ef2-5153-11e7-89d8-43e73ab41af4.png">

Proper position:
![chesslol](https://user-images.githubusercontent.com/20747057/27166996-35443532-5153-11e7-93f6-e2263c3b43d0.png)

**Comment by nnadkarny** [comment]
Resolved in PR #55
